#version: "3.8"
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: riasec-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
      PORT: 3000
      DATABASE_URL: mysql://root:Root_password1@mysql:3306/riasec?schema=public
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

  mysql:
    image: mysql:8.0
    container_name: riasec-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
